ALTER TABLE users
    ADD COLUMN IF NOT EXISTS bio VARCHAR(160) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS location VARCHAR(30) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS website VARCHAR(200) NOT NULL DEFAULT '';
